/* Quatt release-notes manifest — regenerated by the /release-notes skill (Step 8).
   index.html renders this at load; per-release pages live in releases/.
   Newest release first. */

window.SUMMARY = [
  { n: "4",  l: "Releases in the last 60 days" },
  { n: "92", l: "Tickets in latest wave" },
  { n: "5",  l: "Products in latest wave" },
  { n: "2",  l: "Open follow-ups flagged" }
];

window.RELEASES = [
  {
    date: "2026-06-04",
    title: "Quatt Ecosystem Release 04.06.2026",
    badge: { cls: "alpha", label: "alpha → GA track" },
    page: "releases/2026-06-04.html",
    chips: [
      { cls: "cic",   label: "CiC 4.7.0-alpha.0" },
      { cls: "cloud", label: "Cloud v2.38.0–v2.39.1" },
      { cls: "app",   label: "App v1.57.0" },
      { cls: "fw",    label: "Thread FW 2.11.0" },
      { cls: "fw",    label: "Controller 6.8.0" },
      { cls: "fw",    label: "ODU FW 2.1" }
    ],
    stats: [
      { b: "92", t: "tickets" },
      { b: "31", t: "bugs fixed" },
      { b: "3",  t: "flagship themes" },
      { b: "ODUv2 OTA", t: "unlocked" }
    ]
  },
  {
    date: "2026-05-12",
    title: "Quatt Ecosystem Release 12.05.2026",
    badge: { cls: "alpha", label: "alpha · general release" },
    page: "releases/2026-05-12.html",
    chips: [
      { cls: "cic",   label: "CiC 4.6.0-alpha.0" },
      { cls: "cloud", label: "Cloud v2.35.1–v2.37.2" },
      { cls: "app",   label: "App v1.55.0–v1.56.1" },
      { cls: "fw",    label: "Thread FW 2.9.0" },
      { cls: "fw",    label: "Controller 6.7.2" },
      { cls: "fw",    label: "ODU FW 2.0" }
    ],
    stats: [
      { b: "111", t: "tickets" },
      { b: "35",  t: "bugs fixed" },
      { b: "Hybrid commissioning", t: "GA" },
      { b: "ODUv2", t: "hardware launch" }
    ],
    note: "historical backfill"
  }
];
