/* Quatt release-notes manifest — regenerated by the /release-notes skill (Step 8).
   index.html renders this at load; per-release pages live in releases/.
   Newest release first. */

window.SUMMARY = [
  { n: "7",  l: "Release waves documented" },
  { n: "98", l: "Tickets in latest wave" },
  { n: "4",  l: "Products in latest wave" },
  { n: "3",  l: "Open follow-ups flagged" }
];

window.RELEASES = [
  {
    date: "2026-07-16",
    title: "Quatt Ecosystem Release 16.07.2026",
    badge: { cls: "hotfix", label: "hotfix" },
    page: "releases/2026-07-16-4.9.1.html",
    chips: [
      { cls: "cic", label: "CiC 4.9.1" },
      { cls: "fw",  label: "Controller 6.10.3" },
      { cls: "fw",  label: "Thread FW 2.12.0" },
      { cls: "fw",  label: "Chill CB FW 2.0.0" },
      { cls: "fw",  label: "ODU FW 2.1" }
    ],
    stats: [
      { b: "1", t: "ticket" },
      { b: "1", t: "High-priority fix" },
      { b: "QPD-15262", t: "Chill cooling regression fix" },
      { b: "hotfix", t: "stable — to the fleet" }
    ]
  },
  {
    date: "2026-07-16",
    title: "Quatt Ecosystem Release 16.07.2026",
    badge: { cls: "stable", label: "stable (GA)" },
    page: "releases/2026-07-16.html",
    chips: [
      { cls: "cic",   label: "CiC 4.10.0" },
      { cls: "cloud", label: "Cloud v2.42.0" },
      { cls: "app",   label: "App v1.59.0" },
      { cls: "app",   label: "App v1.60.0" },
      { cls: "fw",    label: "Controller 6.11.2" },
      { cls: "fw",    label: "Thread FW 2.13.0" },
      { cls: "fw",    label: "HeatCharger FW 1.3.0" },
      { cls: "fw",    label: "Chill CB FW 2.0.0" },
      { cls: "fw",    label: "ODU FW 2.1" }
    ],
    stats: [
      { b: "98", t: "ticket entries" },
      { b: "App v1.60.0", t: "paired — enables Insights V2 + Boost + sound schedule" },
      { b: "3-way valve", t: "commissioning check end-to-end" },
      { b: "stable", t: "GA — promoted from beta (same build)" }
    ]
  },
  {
    date: "2026-07-03",
    title: "Quatt Ecosystem Release 03.07.2026",
    badge: { cls: "stable", label: "stable (GA)" },
    page: "releases/2026-07-03.html",
    chips: [
      { cls: "cic",   label: "CiC 4.9.0" },
      { cls: "cloud", label: "Cloud v2.41.1–v2.41.2" },
      { cls: "fw",    label: "Controller 6.10.2" },
      { cls: "fw",    label: "Thread FW 2.12.0" },
      { cls: "fw",    label: "Chill CB FW 2.0.0" },
      { cls: "fw",    label: "ODU FW 2.1" }
    ],
    stats: [
      { b: "45", t: "tickets" },
      { b: "ModemManager", t: "LTE stack rebuilt" },
      { b: "MPC", t: "predictive-heating groundwork" },
      { b: "GA", t: "general release (fleet)" }
    ]
  },
  {
    date: "2026-06-30",
    title: "Quatt Ecosystem Release 30.06.2026",
    badge: { cls: "hotfix", label: "hotfix" },
    page: "releases/2026-06-30.html",
    chips: [
      { cls: "cic", label: "CiC 4.8.1" },
      { cls: "fw",  label: "Controller 6.9.2" },
      { cls: "fw",  label: "Thread FW 2.11.1" },
      { cls: "fw",  label: "Chill CB FW 2.0.0" },
      { cls: "fw",  label: "ODU FW 2.1" }
    ],
    stats: [
      { b: "2", t: "tickets" },
      { b: "1", t: "Urgent fix" },
      { b: "Controller 6.9.2", t: "hotfix bump" },
      { b: "Condensation", t: "Chill cooling fix" }
    ]
  },
  {
    date: "2026-06-29",
    title: "Quatt Ecosystem Release 29.06.2026",
    badge: { cls: "stable", label: "stable (GA)" },
    page: "releases/2026-06-29.html",
    chips: [
      { cls: "cic",   label: "CiC 4.8.0" },
      { cls: "cloud", label: "Cloud v2.39.2–v2.40.0" },
      { cls: "fw",    label: "Thread FW 2.11.1" },
      { cls: "fw",    label: "Controller 6.9.0" },
      { cls: "fw",    label: "Chill CB FW 2.0.0" },
      { cls: "fw",    label: "ODU FW 2.1" }
    ],
    stats: [
      { b: "61", t: "tickets" },
      { b: "23", t: "bugs fixed" },
      { b: "3",  t: "flagship themes" },
      { b: "ODUv2 OTA", t: "validated" }
    ]
  },
  {
    date: "2026-06-04",
    title: "Quatt Ecosystem Release 04.06.2026",
    badge: { cls: "stable", label: "stable (GA)" },
    page: "releases/2026-06-04.html",
    chips: [
      { cls: "cic",   label: "CiC 4.7.1" },
      { cls: "cloud", label: "Cloud v2.38.0–v2.39.2" },
      { cls: "app",   label: "App v1.57.0" },
      { cls: "fw",    label: "Thread FW 2.11.0" },
      { cls: "fw",    label: "Controller 6.8.2" },
      { cls: "fw",    label: "ODU FW 2.1" }
    ],
    stats: [
      { b: "124", t: "tickets" },
      { b: "36", t: "bugs fixed" },
      { b: "3",  t: "flagship themes" },
      { b: "ODUv2 OTA", t: "unlocked" }
    ]
  },
  {
    date: "2026-05-12",
    title: "Quatt Ecosystem Release 12.05.2026",
    badge: { cls: "stable", label: "stable" },
    page: "releases/2026-05-12.html",
    chips: [
      { cls: "cic",   label: "CiC 4.6.2" },
      { cls: "cloud", label: "Cloud v2.35.1–v2.39.2" },
      { cls: "app",   label: "App v1.55.0–v1.57.0" },
      { cls: "fw",    label: "Thread FW 2.9.0" },
      { cls: "fw",    label: "Controller 6.7.3" },
      { cls: "fw",    label: "ODU FW 2.0" }
    ],
    stats: [
      { b: "128", t: "tickets" },
      { b: "36",  t: "bugs fixed" },
      { b: "Hybrid commissioning", t: "GA" },
      { b: "ODUv2", t: "hardware launch" }
    ],
    note: "historical backfill"
  }
];
