/* Quatt release-notes manifest — regenerated by the /release-notes skill (Step 8).
   index.html renders this at load; per-release pages live in releases/.
   Newest release first. */

window.SUMMARY = [
  { n: "4",  l: "Releases in the last 60 days" },
  { n: "92", l: "Tickets in latest wave" },
  { n: "5",  l: "Products in latest wave" },
  { n: "2",  l: "Open follow-ups flagged" }
];

window.RELEASES = [
  {
    date: "2026-06-04",
    title: "Quatt Ecosystem Release 04.06.2026",
    badge: { cls: "alpha", label: "alpha → GA track" },
    page: "releases/2026-06-04.html",
    chips: [
      { cls: "cic",   label: "CiC 4.7.0-alpha.0" },
      { cls: "cloud", label: "Cloud v2.38.0–v2.39.1" },
      { cls: "app",   label: "App v1.57.0" },
      { cls: "fw",    label: "Thread FW 2.11.0" },
      { cls: "fw",    label: "Controller 6.8.0" },
      { cls: "fw",    label: "ODU FW 2.1" }
    ],
    stats: [
      { b: "92", t: "tickets" },
      { b: "31", t: "bugs fixed" },
      { b: "3",  t: "flagship themes" },
      { b: "ODUv2 OTA", t: "unlocked" }
    ]
  },
  {
    date: "2026-06-03",
    title: "Quatt Ecosystem Release 03.06.2026",
    badge: { cls: "hotfix", label: "hotfix" },
    page: null,
    chips: [ { cls: "cic", label: "CiC 4.6.1" } ],
    stats: [
      { b: "2", t: "tickets" },
      { b: "", t: "LED status fixes (QPD-14277, QPD-14384)" }
    ],
    note: "covered in the 04.06.2026 notes header"
  },
  {
    date: "2026-05-19",
    title: "Quatt Ecosystem Release 19.05.2026",
    badge: { cls: "stable", label: "stable" },
    page: null,
    chips: [
      { cls: "cic",   label: "CiC 4.6.0" },
      { cls: "cloud", label: "Cloud v2.37.x" },
      { cls: "app",   label: "App v1.56.1" },
      { cls: "fw",    label: "Thread FW 2.9.0" }
    ],
    stats: [
      { b: "~70", t: "tickets" },
      { b: "Chill", t: "field-test stability wave" }
    ],
    note: "predates this dashboard — no detail page"
  },
  {
    date: "2026-04-17",
    title: "Quatt Ecosystem Release 17.04.2026",
    badge: { cls: "stable", label: "stable" },
    page: null,
    chips: [
      { cls: "cic",   label: "CiC 4.5.0" },
      { cls: "cloud", label: "Cloud v2.36.x" },
      { cls: "app",   label: "App v1.55.0" }
    ],
    stats: [
      { b: "~80", t: "tickets" },
      { b: "Hybrid commissioning", t: "GA" }
    ],
    note: "predates this dashboard — no detail page"
  }
];
