// TEST FIXTURE — fake values.
#define SAFETY_SUCTION_CRITICAL_MIN_PRESSURE 0.5f
#define SAFETY_SUCTION_MIN_PRESSURE 1.5f
#define SAFETY_SUCTION_MAX_PRESSURE 9.9f
#define SAFETY_DISCHARGE_MIN_PRESSURE 3.5f
#define SAFETY_DISCHARGE_MAX_PRESSURE 27.9f
#define SAFETY_HEATING_SYSTEM_MIN_PRESSURE 0.9f
#define SAFETY_REFRIGERANT_MIN_CHARGE_PRESSURE 3.1f
#define SAFETY_EQUALIZED_PRESSURE_MAX_DELTA 0.6f
#define SAFETY_COMPRESSION_RATIO_MAX 10.5f
#define SAFETY_SUCTION_MIN_TEMPERATURE 1.5f
#define SAFETY_SUCTION_MAX_TEMPERATURE 65.5f
#define SAFETY_DISCHARGE_MAX_TEMPERATURE 115.5f
#define SAFETY_FREEZING_RISK_INLET_TEMPERATURE 7.5f
#define SAFETY_FREEZING_RISK_OUTLET_TEMPERATURE 5.5f
