// TEST FIXTURE — fake values.
#define SETPOINT_DEGREES 3.5f
#define MINIMUM_EEV_OPEN_RATIO 5.5f
#define MINIMUM_SUPERHEAT 2.5f
#define MINIMUM_SUPERHEAT_PROTECTION 1.6f
#define MINIMUM_SUPERHEAT_PROTECTION_OPEN_RATIO 40.5f
#define MINIMUM_DHW_FLOW_RATE 100.5f
#define DHW_FLOW_HYSTERESIS_MS 3001
#define DHW_FLOW_SUPERHEAT_SETPOINT 4.5f
